### ISSUE TITLE
CloudWatchLogger should not fill the log with exception if cloudwatch is not configured

### ISSUE THREAD

**Issue by totto** [Cantara/ConfigService#50]
2016-06-27 21:02:44.102 [cloudwatch-logger] WARN  n.c.cs.cloudwatch.CloudWatchLogger - Failed to send log events to CloudWatch
com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
    at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131) ~[configservice-0.8-beta-6-20160621.125455-8.jar:na]
    at com.amazonaws.http.AmazonHttpClient.getCredentialsFromContext(AmazonHttpClient.java:763) ~[configservice-0.8-beta-6-20160621.125455-8.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:789) ~[configservice-0.8-beta-6-20160621.125455-8.jar:na]

**Comment by sindremehus** [comment]
This is controlled by the property "cloudwatch.enabled".

I've now set it to be false by default.
